name: Sync PR from main into develop

on:
  push:
    branches:
      - main

jobs:
  sync-develop:
    name: Create PR from main into develop
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 4
          
      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          

      - name: Create Pull Request if there are changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest commit message and hash
          COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Ensure branches are up to date
          git fetch origin develop
          git fetch origin main
          
          # Compare the actual content state between branches using diff-tree
          DIFF_COUNT=$(git diff-tree -r --ignore-space-at-eol origin/main origin/develop -- . ':!.github/workflows/sync-develop.yaml' | wc -l)
          
          if [ "$DIFF_COUNT" -eq "0" ]; then
            echo "[SKIPPED]No changes to sync - develop is already up to date with main"
            exit 0
          fi
          
          echo "Found $DIFF_COUNT files with differences between main and develop"
          
          # Create a new branch from main
          SYNC_BRANCH="sync/main-to-develop-${COMMIT_HASH:0:7}"
          git checkout develop && git pull origin develop && git push origin develop
          git checkout main && git pull origin main
          git checkout -b $SYNC_BRANCH
          git push origin $SYNC_BRANCH
          
          # Try to create PR
          gh pr create \
            --base develop \
            --head main \
            --title "chore: sync main into develop (${COMMIT_HASH:0:7})" \
            --body "This PR was automatically created to sync changes from main into develop.

            **Changes included:**
            ${COMMIT_MSG}
            
            This PR was triggered by commit: ${COMMIT_HASH}" \
            --label "automated-sync" \
            --assignee "paanSinghCoder" || echo "PR creation failed, likely because PR already exists"