name: Create PR from main to develop

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-develop:
    name: Create PR from main to develop
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Fetch all branches
        run: |
          git fetch origin develop:develop || git branch develop

      - name: Create Pull Request if there are changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest commit message and hash
          COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Check if there are any differences between main and develop
          if git diff --quiet main develop; then
            echo "No changes to sync - develop is already up to date with main"
            exit 0
          fi
          
          # Create a new branch from main
          SYNC_BRANCH="sync/main-to-develop-${COMMIT_HASH:0:7}"
          git checkout -b $SYNC_BRANCH
          git push origin $SYNC_BRANCH
          
          # Try to create PR
          gh pr create \
            --base develop \
            --head $SYNC_BRANCH \
            --title "chore: sync develop with main (${COMMIT_HASH:0:7})" \
            --body "This PR was automatically created to sync changes from main into develop.

            **Changes included:**
            ${COMMIT_MSG}
            
            This PR was triggered by commit: ${COMMIT_HASH}" \
            --label "automated-sync" || echo "PR creation failed, likely because PR already exists"